"""add training_jobs

Revision ID: 16a61971c84b
Revises: c3714b03142e
Create Date: 2026-06-07 09:18:09.172563
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = '16a61971c84b'
down_revision: Union[str, None] = 'c3714b03142e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_model', sa.String(length=120), nullable=False),
    sa.Column('file_ids', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='trainingstatus', native_enum=False), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('result_preset_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_status'))

    op.drop_table('training_jobs')
    # ### end Alembic commands ###
