"""initial schema

Revision ID: 7613fb147cbe
Revises: 
Create Date: 2026-06-05 21:50:59.720073
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = '7613fb147cbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('files',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('tier', sa.Enum('hot', 'cold', name='storagetier', native_enum=False), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_owner_id'), ['owner_id'], unique=False)

    op.create_table('render_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='renderstatus', native_enum=False), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('output_file_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['output_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_render_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_jobs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_render_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_render_jobs_status'))

    op.drop_table('render_jobs')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_owner_id'))

    op.drop_table('files')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
