"""render_jobs add is_public

Revision ID: 4a579b1d7f48
Revises: fecf0807872d
Create Date: 2026-06-06 21:19:41.520311
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a579b1d7f48'
down_revision: Union[str, None] = 'fecf0807872d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_render_jobs_is_public'), ['is_public'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_render_jobs_is_public'))
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
