"""add render_jobs.external_job_id

Revision ID: 4ca3d26969dd
Revises: 7613fb147cbe
Create Date: 2026-06-06 10:54:39.799052
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4ca3d26969dd'
down_revision: str | None = '7613fb147cbe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_job_id', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.drop_column('external_job_id')

    # ### end Alembic commands ###
