"""add studio_presets

Revision ID: fecf0807872d
Revises: 8dda2f6d6d46
Create Date: 2026-06-06 20:08:25.117865
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fecf0807872d'
down_revision: Union[str, None] = '8dda2f6d6d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_presets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_presets_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_presets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_presets_user_id'))
        batch_op.drop_index(batch_op.f('ix_studio_presets_kind'))

    op.drop_table('studio_presets')
    # ### end Alembic commands ###
