"""studio_presets add is_public

Revision ID: c3714b03142e
Revises: 086850107bd4
Create Date: 2026-06-07 09:08:15.486686
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3714b03142e'
down_revision: Union[str, None] = '086850107bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_studio_presets_is_public'), ['is_public'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_presets_is_public'))
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
